services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://root:team3@mongodb:27017/?authSource=admin
    networks:
      - shared_network

networks:
  shared_network:
    external: true
